
```{r echo=F}
## Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, dplyr, ggplot2, data.table, lubridate,
               plotROC, usmap, glmnet, car)


knitr::opts_chunk$set(echo = F, cache = T, fig.width=10, fig.height=4,
                      warning = F, results = "hide", message=F)
options(scipen = 0, digits = 3)  ## controls base R output
```


```{r}
## Load data
vaccination_policy <- fread('../Data/COVID-19 Response International/covid-vaccination-policy.csv')

vaccination_policy <- vaccination_policy[Day > as.IDate("2020-12-01")]
vaccination_policy$Month <- format(vaccination_policy$Day,format="%y-%m-01")

vaccination_policy_month <- vaccination_policy %>% 
    group_by(Month, Code) %>% 
    summarise(month_avg = mean(vaccination_policy))

vaccination_policy_month$Month <- as.IDate(vaccination_policy_month$Month)

ggplot(vaccination_policy_month, aes(x = Month, y = month_avg, color = Code)) +
  geom_line()+
  geom_point() +
  theme_bw() +
  theme(legend.position = "none")
```

```{r}
## Load data
public_campaigns <- fread('../Data/COVID-19 Response International/public-campaigns-covid.csv')

public_campaigns <- public_campaigns[Day > as.IDate("2020-12-01")]
public_campaigns$Month <- format(public_campaigns$Day,format="%y-%m-01")

public_campaigns_month <- public_campaigns %>% 
    group_by(Month, Code) %>% 
    summarise(month_avg = mean(public_information_campaigns))

public_campaigns_month$Month <- as.IDate(public_campaigns_month$Month)

ggplot(public_campaigns_month, aes(x = Month, y = month_avg, color = Code)) +
  geom_line()+
  geom_point() +
  theme_bw() +
  theme(legend.position = "none")
```

```{r}
## Load data
school_closures <- fread('../Data/COVID-19 Response International/school-closures-covid.csv')

school_closures <- school_closures[Day > as.IDate("2020-12-01")]
school_closures$Month <- format(school_closures$Day,format="%y-%m-01")

school_closures_month <- school_closures %>% 
    group_by(Month, Code) %>% 
    summarise(month_avg = mean(school_closures))

school_closures_month$Month <- as.IDate(school_closures_month$Month)

ggplot(school_closures_month, aes(x = Month, y = month_avg, color = Code)) +
  geom_line()+
  geom_point() +
  theme_bw() +
  theme(legend.position = "none")
```

```{r}
## Load data
sah <- fread('../Data/COVID-19 Response International/stay-at-home-covid.csv')

sah <- sah[Day > as.IDate("2020-12-01")]
sah$Month <- format(sah$Day,format="%y-%m-01")

sah_month <- sah %>% 
    group_by(Month, Code) %>% 
    summarise(month_avg = mean(stay_home_requirements))

sah_month$Month <- as.IDate(sah_month$Month)

ggplot(sah_month, aes(x = Month, y = month_avg, color = Code)) +
  geom_line()+
  geom_point() +
  theme_bw() +
  theme(legend.position = "none")
```