```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, results="show", fig.width=9, fig.height=6, warning=FALSE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(tidyverse, dplyr, ggplot2, data.table, lubridate,
               plotROC, usmap, glmnet, car, rworldmap, countrycode)
```

```{r}
GDP <- fread('GDP.csv')
# GDP <- GDP[Period=="Q1-2019"]
# GDP <- GDP[MEASURE!="HCPCARSA"]
# GDP <- GDP[Country!="G7"]
# GDP <- GDP[Country!="NAFTA"]
# GDP <- GDP[Country!="OECD - Total"]
# GDP <- GDP[Country!="OECD - Europe"]
# GDP <- GDP[Country!="European Union – 27 countries (from 01/02/2020)"]
# GDP <- GDP[Country!="Euro area (19 countries)"]
GDP <- GDP[V2!="Country Code"]
GDP$V2 <- countrycode(GDP$V2, origin="wb", destination="iso3c")
GDP <- GDP %>% filter(!is.na(V2)) %>% filter(!is.na(V64))
GDP$V64 <- log(GDP$V64/1000)

mapped_data <- joinCountryData2Map(GDP, joinCode = "ISO3", 
    nameJoinColumn = "V2")

par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(mapped_data, nameColumnToPlot = "V64")

GDPSort <- GDP %>% arrange(desc(Global Economy and GDP)) %>% select(V1, V2, V64)
```

```{r}
GDPMiddle <- GDPSort[94:104]
GDPBot <- GDPSort[183:198]
GDPTop <- GDPSort[1:5]

df <- data.frame(country=rep("", 32),
                 gdp=rep(0,32),
                 code=rep("",32))
df$country <- c(GDPTop$V1, GDPMiddle$V1, GDPBot$V1)
df$code <- c(GDPTop$V2, GDPMiddle$V2, GDPBot$V2)
df$gdp <- c(GDPTop$V64, GDPMiddle$V64, GDPBot$V64)
```