---
title: "Top Countries Population"
output: html_document
---
```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, results="show", fig.width=8, fig.height=4, warning=FALSE)
options(scipen = 0, digits = 3)  # controls base R output
# check if you have ISLR package, if not, install it
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, magrittr, dplyr, ggplot2, ggthemes,car,gapminder)
```

```{r Load data}
pop <- read.csv("~/Documents/GitHub/Penn/upenn-data-science-academy/Final Project/Data/OECD Data/top_countries_population.csv")
```

```{r}
pop <- pop %>% select(Country,TIME,Value)

Year <- pop$TIME
Value <- pop$Value
Country <- pop$Country
 

```

```{r}
pop %>% 
  ggplot(aes(x = Year, y = Value)) +
  geom_line(aes(group = Country, col = Country)) +
  geom_point(aes(group = Country, col = Country)) +
  labs(x = "Year", y="Population") +
  scale_x_continuous(breaks = seq(2018,2030, by = 1)) + 
  ggtitle('Project Population of Top Countries in terms of GDP') + 
  theme(plot.title = element_text(hjust = 0.5))
```

